### PR TITLE
Added PeerTube to the list

### PR DESCRIPTION
**Pull request by rsolvang**
Just added PeerTube to the list. It's a great tool to build a community around video content, without being at the mercy of Youtube.

### CODE REVIEW

**Comment by e8johan** [comment]
PeerTube is listed as a video publishing platform further down (we use conf.tube). As far as I can tell, PeerTube cannot be used for video broadcasting (live streaming). Could you refer me to how to do that with PeerTube and I'll try to get conf.tube upgraded and merge this.

**Comment by rsolvang** [comment]
Sorry, I was to quick to add my suggestion! Should have read the whole document first :blush:
After looking around a bit, I stumbled upon [Open Streaming Platform](https://gitlab.com/Deamos/flask-nginx-rtmp-manager/-/blob/master/README.md), which seems to be a more appropriate suggestion.

**Comment by e8johan** [comment]
Nice. Would you mind updating the PR and I'll merge it with Open Streaming Platform instead.

**Comment by e8johan** [comment]
Thanks a lot! Merged!

**Pull request merged**
